dist: Xenial
os: linux
sudo: required
services :
  - mysql
language: python
python: 3.4
before_install:
  - sudo pip install virtualenv
  - virtualenv --python=python3 venv
  - pip install -r requirements.txt
script:
  - echo "hi Travis"
